/**
 * Fun Reading:
 *
 * - https://developers.google.com/web/tools/workbox/guides/common-recipes
 * - https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68
 */

// Packages: https://github.com/GoogleChrome/workbox/tree/master/packages
import { skipWaiting } from 'workbox-core/skipWaiting';
import { clientsClaim } from 'workbox-core/clientsClaim';
import { precacheAndRoute } from 'workbox-precaching/precacheAndRoute.mjs';
import { registerRoute } from 'workbox-routing/registerRoute';
import { StaleWhileRevalidate } from 'workbox-strategies/StaleWhileRevalidate';
import { CacheFirst } from 'workbox-strategies/CacheFirst';
import { CacheableResponsePlugin } from 'workbox-cacheable-response/CacheableResponsePlugin';
import { ExpirationPlugin } from 'workbox-expiration/ExpirationPlugin';

// https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_the_waiting_phase
skipWaiting();
// https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#clientsclaim
clientsClaim();

// Font File and Font Stylesheet Caching
// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
registerRoute(
  /^https:\/\/fonts\.googleapis\.com/,
  StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
registerRoute(
  /^https:\/\/fonts\.gstatic\.com/,
  CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

// PreCache everything generated by WebPack
precacheAndRoute(self.__precacheManifest);
